### ISSUE TITLE
Row and column labels for Custom.Matrix

### ISSUE THREAD

**Issue by rockt** [sameersingh/htmlgen#7]
Something like this: http://rockt.github.io/slides/2015-cambridge/graphics/MF-1.png

**Comment by sameersingh** [comment]
You can add html code in the string as well, so coloring text should be simple.

If you use multiple words, then it'll split it and look ugly, thus use `&nbsp;` instead of spaces.

**Comment by rockt** [comment]
Pretty cool! Could the column and row headers be resized depending on the length of the strings? Currently it looks like this...
![screen shot 2015-05-23 at 12 00 31](https://cloud.githubusercontent.com/assets/1196835/7783715/7b1febee-0143-11e5-8013-6f6d6ccdee49.png)

**Comment by rockt** [comment]
Also, would be good to have a different background color for the headers so that they are not confused with predictions (white/black).

**Comment by sameersingh** [comment]
Added a change to htmlgen.css to make this look better, also propagated to moro and its wolfe.css.
